const data = [
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
  {
    name: "상품 이름",
    description: "상품에 대한 설명을 작성해주세요.",
    price: 15000,
    manufacturer: "상품 제조사",
    tags: ["전자제품", "테스트"],
    favoriteCount: 0,
  },
];

export default data;
