###상품 좋아요
POST http://localhost:3000/favorites/product/11   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzA0NDQxMSwiZXhwIjoxNzQ3MDQ4MDExfQ.NZP7XfvV_VrKRNnVJXlb7WN5paBmN8migSSxmTfjKQE


###상품 좋아요 취소
DELETE http://localhost:3000/favorites/product/11    
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzA0MDgxNiwiZXhwIjoxNzQ3MDQ0NDE2fQ.IZvkmL8WFZ1wFBqX5fMmVtSaxnPOqm4pUEw-ZA7eFxg

###게시글 좋아요
POST http://localhost:3000/favorites/article/:id       
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzA0MDgxNiwiZXhwIjoxNzQ3MDQ0NDE2fQ.IZvkmL8WFZ1wFBqX5fMmVtSaxnPOqm4pUEw-ZA7eFxg

###게시글 좋아요 취소
DELETE http://localhost:3000/favorites/article/:id       
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzA0MDgxNiwiZXhwIjoxNzQ3MDQ0NDE2fQ.IZvkmL8WFZ1wFBqX5fMmVtSaxnPOqm4pUEw-ZA7eFxg