###상품 등록
POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTc0NzEyNTUxNiwiZXhwIjoxNzQ3MTI5MTE2fQ.BRRMn_GvmgjVbX44r26cB9jxrZfjZn-p-Zmg4TnDqS8

{
    "name": "authorId 등록2" ,
    "description": "authorId 등록" ,
    "price": 10000,
    "tags": "인증된"

}

###상품 좋아요 등록
POST http://localhost:3000/products/9/favorite
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjY4NDI0MCwiZXhwIjoxNzQ2Njg3ODQwfQ.SOESrOEWFQEA_1_MI6Ftwd8o_iZ9V3WwRfuUmIv4bTk

{
    "name": "상품9" ,
    "description": "9번째 상품" ,
    "price": 11111,
    "tags": ["인증된"]

}

###상품 좋아요 삭제
DELETE http://localhost:3000/products/9/favorite
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjY4NDI0MCwiZXhwIjoxNzQ2Njg3ODQwfQ.SOESrOEWFQEA_1_MI6Ftwd8o_iZ9V3WwRfuUmIv4bTk

{
    "name": "상품9" ,
    "description": "9번째 상품" ,
    "price": 11111,
    "tags": ["인증된"]

}

###상품 목록 조회
GET http://localhost:3000/products?page=1&pageSize=10&orderBy=recent&keyword=2

###베스트 상품 목록 조회
GET http://localhost:3000/products?page=1&pageSize=4&orderBy=favorite


###상품 상세 조회
GET http://localhost:3000/products/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzEwMjUxNiwiZXhwIjoxNzQ3MTA2MTE2fQ.tsuULPTa5EPZ79Aw4ltt0MBi--u08zf74ShDpueR26A


###상품 수정
PATCH http://localhost:3000/products/9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjY4NDI0MCwiZXhwIjoxNzQ2Njg3ODQwfQ.SOESrOEWFQEA_1_MI6Ftwd8o_iZ9V3WwRfuUmIv4bTk

{
    "name": "상품8-1" ,
    "description": "8번째 상품" ,
    "price": 88888,
    "tags": ["인증 후 수정"]
}

###상품 삭제
DELETE http://localhost:3000/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NjY4NDI0MCwiZXhwIjoxNzQ2Njg3ODQwfQ.SOESrOEWFQEA_1_MI6Ftwd8o_iZ9V3WwRfuUmIv4bTk


### 상품 댓글 등록
POST http://localhost:3000/products/11/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0NzAzMDAyNCwiZXhwIjoxNzQ3MDMzNjI0fQ.tjpKBgU__Ql3Qwb7F1m1oRuM6pPa5crBAtNnYdH0PCA

{
    "content": "저 코다마 사고싶어요"
}

###상품 댓글 목록 조회
GET http://localhost:3000/products/11/comments