import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 폰트 설정 (변수 등록)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 메타데이터 (타입 자동 추론됨)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 컴포넌트에 props 타입 명시
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-pretendard antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
