import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavIndexProvider from "@/providers/NavIndexProvider";
import { ArticlesProvider } from "@/providers/ArticlesProvider";
import AuthProvider from "@/providers/AuthProvider";
import EmptyLayout from "@/components/commonLayout/EmptyLayout";
import RouteGuard from "@/providers/RouteGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <RouteGuard>
            <NavIndexProvider>
              <ArticlesProvider>
                <EmptyLayout>
                  <main className="flex-1">{children}</main>
                </EmptyLayout>
              </ArticlesProvider>
            </NavIndexProvider>
          </RouteGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
