import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import NavIndexProvider from "@/providers/NavIndexProvider";
import { ArticlesProvider } from "@/providers/ArticlesProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <NavIndexProvider>
          <ArticlesProvider>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </ArticlesProvider>
        </NavIndexProvider>
      </body>
    </html>
  );
}
